version: '2'
services:
  web:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8069
      unhealthy_threshold: 60
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/?debug=assets" "HTTP/1.0"
  connector:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8069
      unhealthy_threshold: 60
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
  cron:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8069
      unhealthy_threshold: 60
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
  db-utils:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
